# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.21.6


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))

In [4]:
# Method 2
a = np.random.randn(2, 3, 5)

In [5]:
# Method 3
a = np.random.randint(0, 100, size=(2, 3, 5))

#### 4. Print *a*.


In [6]:
# your code here
a = np.random.random((2,3,5))
print(a)
type(a)
a.dtype

[[[0.5115532  0.33652852 0.33231183 0.99972192 0.43782468]
  [0.60676362 0.69300215 0.07208918 0.79044679 0.33167534]
  [0.97335321 0.84609929 0.70009501 0.14676816 0.46621855]]

 [[0.68491609 0.71977194 0.8313485  0.61732763 0.26315098]
  [0.10228877 0.7772326  0.79758226 0.81306106 0.77200353]
  [0.9013301  0.83777822 0.86290403 0.68338217 0.88486872]]]


dtype('float64')

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)
b.dtype

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


dtype('float64')

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
if a.size==b.size:
    print(f'the size of a and b is {a.size}')
else:
    print(f'the size of a is {a.size} and the size of b is {b.size}')

the size of a and b is 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here
print(np.add(a, b))
# This formula returns an error because a and b have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here
d = np.add(a, c)
print(d)
# Now it works because we have two arrays with the same shape

[[[1.5115532  1.33652852 1.33231183 1.99972192 1.43782468]
  [1.60676362 1.69300215 1.07208918 1.79044679 1.33167534]
  [1.97335321 1.84609929 1.70009501 1.14676816 1.46621855]]

 [[1.68491609 1.71977194 1.8313485  1.61732763 1.26315098]
  [1.10228877 1.7772326  1.79758226 1.81306106 1.77200353]
  [1.9013301  1.83777822 1.86290403 1.68338217 1.88486872]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
# your code/answer here
print(a)
print('\n')
print(d)
# d is same as a plus 1.

[[[0.5115532  0.33652852 0.33231183 0.99972192 0.43782468]
  [0.60676362 0.69300215 0.07208918 0.79044679 0.33167534]
  [0.97335321 0.84609929 0.70009501 0.14676816 0.46621855]]

 [[0.68491609 0.71977194 0.8313485  0.61732763 0.26315098]
  [0.10228877 0.7772326  0.79758226 0.81306106 0.77200353]
  [0.9013301  0.83777822 0.86290403 0.68338217 0.88486872]]]


[[[1.5115532  1.33652852 1.33231183 1.99972192 1.43782468]
  [1.60676362 1.69300215 1.07208918 1.79044679 1.33167534]
  [1.97335321 1.84609929 1.70009501 1.14676816 1.46621855]]

 [[1.68491609 1.71977194 1.8313485  1.61732763 1.26315098]
  [1.10228877 1.7772326  1.79758226 1.81306106 1.77200353]
  [1.9013301  1.83777822 1.86290403 1.68338217 1.88486872]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [17]:
# your code here
e = np.multiply(a, c)
print(e)

[[[0.5115532  0.33652852 0.33231183 0.99972192 0.43782468]
  [0.60676362 0.69300215 0.07208918 0.79044679 0.33167534]
  [0.97335321 0.84609929 0.70009501 0.14676816 0.46621855]]

 [[0.68491609 0.71977194 0.8313485  0.61732763 0.26315098]
  [0.10228877 0.7772326  0.79758226 0.81306106 0.77200353]
  [0.9013301  0.83777822 0.86290403 0.68338217 0.88486872]]]


numpy.ndarray

#### 13. Does *e* equal to *a*? Why or why not?


In [19]:
# your code/answer here
print(type(e))
print(type(a))
print(e.dtype)
print(a.dtype)
print(e.itemsize)
print(a.itemsize)
# Yes, both arrays are equal, similar logic as if we multiply any value by 1

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
float64
float64
8
8


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [25]:
# your code here
d_max = d.max()
print(d_max)
d_min = d.min()
print(d_min)
d_mean = d.mean()
print(d_mean)

1.9997219222314588
1.0720891786900826
1.6264466021740382


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [28]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [32]:
# your code here
for value in d:
    index==0
    if d_min < value < d_mean:
        f[index]==25
        index += 1
    elif d_mean < value < d_max:
        f[index]==75
        index += 1
    elif value == d_mean:
        f[index]==50
        index += 1
    elif value == d_min:
        f[index]==0
        index += 1
    elif value == d_max:
        f[index]==100
        index += 1

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here