# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np   #importamos numpy como np especificandolo para poder recortar el nombre
                        # OJO: estar pendiente de estar en el ambiente adecuado para trabajar en este caso el (m1) 

#### 2. Print your NumPy version.

In [2]:
print(np.__version__) #vemos cual tenemos instalada 

1.26.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [18]:
a = np.random.rand(2, 3, 5) #usamos el metodo np.random.rand() Para números flotantes uniformemente distribuidos
print(a)

[[[0.20528675 0.6756216  0.18593953 0.05840284 0.46897541]
  [0.28263432 0.02486309 0.1091883  0.52890055 0.38619572]
  [0.52519067 0.28666524 0.96147864 0.51568056 0.0590663 ]]

 [[0.78017876 0.22990805 0.48375919 0.85265229 0.79723507]
  [0.88751119 0.42534811 0.58792493 0.17460669 0.95784173]
  [0.33053847 0.73939973 0.11220932 0.46981093 0.86735609]]]


In [19]:
a = np.random.randn(2, 3, 5) # #usamos el metodo np.random.randn() Para números flotantes normalmente distribuidos
print(a)                         #muy parecido al primer metodo 

[[[ 1.72839626  0.93102556  1.50559746 -0.31988604  0.90252892]
  [-0.13590207  0.55419181  1.0942049   0.27280669  2.89814153]
  [ 0.552704    1.03971106 -1.18867092 -0.73360039 -0.36029416]]

 [[ 0.24767595 -0.31471609  0.03389453 -0.39449639 -1.90178266]
  [-1.42197261 -0.96271032  0.32134351 -0.99214993  0.82139229]
  [-1.69927111  0.74154541  0.57087937 -0.60956199  0.51065612]]]


In [46]:
a = np.random.randint(0, 10, size=(2, 3, 5)) #usamos el metodo np.random.randint() especificando de que numero a que numero crear los elementos aleatorios y el tamaño del objeto de clase  numpy.ndarray  que queromos crear 
print(a_3)


[[[8 4 0 1 8]
  [9 8 0 9 9]
  [8 0 3 8 4]]

 [[4 8 3 5 7]
  [4 6 3 7 4]
  [5 8 7 9 5]]]


In [64]:
print(type(a))


<class 'numpy.ndarray'>


#### 4. Print *a*.


In [47]:
print(a)

[[[5 4 9 2 7]
  [3 1 6 7 9]
  [2 6 0 8 3]]

 [[1 6 2 3 1]
  [3 6 2 2 8]
  [6 1 8 7 1]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [65]:
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [66]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [69]:
print(a.size) #usamos el metodo size. para ver el tamaño del obajeto 
print(b.size) #vemos que tienen el mismo size 

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [73]:
sum_a_b = a + b # no se podria agregar la matices a en b porque sus formas no son iguales a pesar de tener el mismo size

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [77]:
c = b.transpose() #usamos el metodo transpos para que nos de c como resultado 
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [79]:
d = a + c #vemos que tampoco funciona debido a que ahora seria deforma (3,2,5) y tampoco seria compatible 

ValueError: operands could not be broadcast together with shapes (2,3,5) (3,2,5) 

In [86]:
print(c)
print(c.shape) #vemos la forma


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


In [87]:
c = c.reshape(2,3,5) #usamos la funcion reshape y le especificamos la forma que queremos.
print(c)            #vemos que ahora tienen las mis forma 

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [91]:
d = a + c
print(d)

[[[ 6.  5. 10.  3.  8.]
  [ 4.  2.  7.  8. 10.]
  [ 3.  7.  1.  9.  4.]]

 [[ 2.  7.  3.  4.  2.]
  [ 4.  7.  3.  3.  9.]
  [ 7.  2.  9.  8.  2.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [93]:
print(a)
print(d)
print(type(a))
print(type(d))

[[[5 4 9 2 7]
  [3 1 6 7 9]
  [2 6 0 8 3]]

 [[1 6 2 3 1]
  [3 6 2 2 8]
  [6 1 8 7 1]]]
[[[ 6.  5. 10.  3.  8.]
  [ 4.  2.  7.  8. 10.]
  [ 3.  7.  1.  9.  4.]]

 [[ 2.  7.  3.  4.  2.]
  [ 4.  7.  3.  3.  9.]
  [ 7.  2.  9.  8.  2.]]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
# your code here

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here