# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [125]:
import numpy as np   #importamos numpy como np especificandolo para poder recortar el nombre
                        # OJO: estar pendiente de estar en el ambiente adecuado para trabajar en este caso el (m1) 

#### 2. Print your NumPy version.

In [126]:
print(np.__version__) #vemos cual tenemos instalada 

1.26.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [127]:
a = np.random.rand(2, 3, 5) #usamos el metodo np.random.rand() Para números flotantes uniformemente distribuidos
print(a)

[[[0.70524467 0.92484708 0.60788826 0.54061579 0.98390266]
  [0.44563475 0.63523371 0.42632917 0.18955444 0.24271917]
  [0.14429531 0.16216711 0.8606115  0.06657928 0.3703588 ]]

 [[0.49945797 0.21431872 0.26103199 0.75745394 0.00116557]
  [0.62750059 0.30780527 0.70546229 0.22937943 0.17385642]
  [0.57700811 0.41437224 0.6738838  0.08656576 0.97863397]]]


In [128]:
a = np.random.randn(2, 3, 5) # #usamos el metodo np.random.randn() Para números flotantes normalmente distribuidos
print(a)                         #muy parecido al primer metodo 

[[[-0.62084318 -1.65336524 -0.48176395  0.3314338   1.10228967]
  [-1.20742166 -1.3379913   1.56060033 -0.67366119  1.01177791]
  [ 0.64394706  0.15191885  1.21670825 -1.21967353 -1.27310999]]

 [[ 0.33711312  1.12438946 -0.89580373  0.82403255 -1.13459342]
  [ 2.59791274  1.00049607  2.1335266   0.16389907 -0.11777927]
  [-0.26290382 -0.28464848  0.739484    0.59268939 -0.74119297]]]


In [129]:
a = np.random.randint(0, 10, size=(2, 3, 5)) #usamos el metodo np.random.randint() especificando de que numero a que numero crear los elementos aleatorios y el tamaño del objeto de clase  numpy.ndarray  que queromos crear 
print(a_3)


[[[8 4 0 1 8]
  [9 8 0 9 9]
  [8 0 3 8 4]]

 [[4 8 3 5 7]
  [4 6 3 7 4]
  [5 8 7 9 5]]]


In [130]:
print(type(a))


<class 'numpy.ndarray'>


#### 4. Print *a*.


In [131]:
print(a)

[[[4 3 5 7 5]
  [3 2 9 4 7]
  [6 0 9 8 5]]

 [[5 4 4 1 0]
  [7 5 4 5 4]
  [8 3 2 0 6]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [132]:
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [133]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [134]:
print(a.size) #usamos el metodo size. para ver el tamaño del obajeto 
print(b.size) #vemos que tienen el mismo size 

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [73]:
sum_a_b = a + b # no se podria agregar la matices a en b porque sus formas no son iguales a pesar de tener el mismo size

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [135]:
c = b.transpose() #usamos el metodo transpos para que nos de c como resultado 
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [136]:
d = a + c #vemos que tampoco funciona debido a que ahora seria deforma (3,2,5) y tampoco seria compatible 

ValueError: operands could not be broadcast together with shapes (2,3,5) (3,2,5) 

In [139]:
print(c)
print(c.shape) #vemos la forma


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(3, 2, 5)


In [151]:
c = c.reshape(2,3,5) #usamos la funcion reshape y le especificamos la forma que queremos.
print(c)            #vemos que ahora tienen las mis forma 

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [154]:
d = a + c
print(d)

[[[ 5.  4.  6.  8.  6.]
  [ 4.  3. 10.  5.  8.]
  [ 7.  1. 10.  9.  6.]]

 [[ 6.  5.  5.  2.  1.]
  [ 8.  6.  5.  6.  5.]
  [ 9.  4.  3.  1.  7.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [155]:
print(a)             # en el conjunto a esta el original y en el elemenyo d esta los elementos de a mas los elemntos de c.
print(d)             # podemos con cluir que podemos sumar numpys con la misma forma para que puedan ser compatibles
print(type(a))
print(type(d))

[[[4 3 5 7 5]
  [3 2 9 4 7]
  [6 0 9 8 5]]

 [[5 4 4 1 0]
  [7 5 4 5 4]
  [8 3 2 0 6]]]
[[[ 5.  4.  6.  8.  6.]
  [ 4.  3. 10.  5.  8.]
  [ 7.  1. 10.  9.  6.]]

 [[ 6.  5.  5.  2.  1.]
  [ 8.  6.  5.  6.  5.]
  [ 9.  4.  3.  1.  7.]]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [156]:
e = a * c #vemos que podemos hacer operaciones matematicas y cada elemento se multiplica por el otro elemento en su misma posicion 
print (e)

[[[4. 3. 5. 7. 5.]
  [3. 2. 9. 4. 7.]
  [6. 0. 9. 8. 5.]]

 [[5. 4. 4. 1. 0.]
  [7. 5. 4. 5. 4.]
  [8. 3. 2. 0. 6.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [157]:
 e == a #vemos que si son iguales en todo sentido 
    

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [158]:
d_max = np.max(d)  # usamos el metodo que nos devuelve el valor mas alto 
d_min = np.min(d)  # usamos el metodo que nos devuelve el valor mas bajo 
d_mean = np.mean(d) # usamos el metodo que nos devuelve el valor medio de los elementos
print(d_max)
print(d_min)
print(d_mean)
print(type(d_max))
print(type(d_min))
print(type(d_mean))

10.0
1.0
5.5
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [159]:
f = np.empty(d.shape) #creamos una matriz vacia con la forma de d usando  np.empty(d.shape) 
print(f)

[[[4. 3. 5. 7. 5.]
  [3. 2. 9. 4. 7.]
  [6. 0. 9. 8. 5.]]

 [[5. 4. 4. 1. 0.]
  [7. 5. 4. 5. 4.]
  [8. 3. 2. 0. 6.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [169]:
#nos piden definir unas condiciones especificas para los valores de cada posicion. vemos que podemos usar los numpy pata hacerlo
#especificando el parametro.#fpara referirinos a nuestra matriz vacia 
f[(d == d_min)] = 0     #especificamos que para los elementos en d si es igual al d_min(valor mas bajo)use un 0
f[(d == d_mean)] = 50   #especificamos igual mente que si el elemento es igual al d_mean(valor medio) use un 50
f[(d == d_max)] = 100  #especificamos que si el valor es igual al d_max (valor mas alto)use 100
f[(d_min < d) & (d < d_mean)] = 25#en las que tenemos dos condiciones. si d es mayor que d_min pero menor que la d_mean use el 25
f[(d_mean < d) & (d < d_max)] = 75# si d es mayor que la media y d es menor que la d_max use un 75
print(f) #vemos que nos funcion 
print(type(f[1,1,1]))#vemos que los elementos dentro son numpy.float64

[[[ 25.  25.  75.  75.  75.]
  [ 25.  25. 100.  25.  75.]
  [ 75.   0. 100.  75.  75.]]

 [[ 75.  25.  25.  25.   0.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  25.  25.   0.  75.]]]
<class 'numpy.float64'>


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [161]:
print(d)
print(f)

[[[ 5.  4.  6.  8.  6.]
  [ 4.  3. 10.  5.  8.]
  [ 7.  1. 10.  9.  6.]]

 [[ 6.  5.  5.  2.  1.]
  [ 8.  6.  5.  6.  5.]
  [ 9.  4.  3.  1.  7.]]]
[[[ 25.  25.  75.  75.  75.]
  [ 25.  25. 100.  25.  75.]
  [ 75.   0. 100.  75.  75.]]

 [[ 75.  25.  25.  25.   0.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  25.  25.   0.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [166]:
g = np.empty(d.shape ,dtype=object)#al pedirnos que usemos un string como marcador tenemos que especificar el tipo de dato debido a que tenemos numpy.float64 dentro de la matriz
print(g)                # y si no lo hacemos nos dara un error al especificar el dtype=object nos permite almacenar string 
                       #y volvemos a seguir los paso de crear una matriz vacia y pero con el tipo de dato que nos onteresa 

[[[None None None None None]
  [None None None None None]
  [None None None None None]]

 [[None None None None None]
  [None None None None None]
  [None None None None None]]]


In [170]:
g[(d == d_min)] = "A"    #usamos la mis forma y solo sutituimos el marcador que queremos usar que ahora seria un string 

g[(d == d_mean)] = "C"
g[(d == d_max)] = "E"
g[(d_min < d) & (d < d_mean)] = "B"
g[(d_mean < d) & (d < d_max)] = "D"
print(g)
print(type(g))

[[['B' 'B' 'D' 'D' 'D']
  ['B' 'B' 'E' 'B' 'D']
  ['D' 'A' 'E' 'D' 'D']]

 [['D' 'B' 'B' 'B' 'A']
  ['D' 'D' 'B' 'D' 'B']
  ['D' 'B' 'B' 'A' 'D']]]
<class 'numpy.ndarray'>
